# Generated by Django 4.2.4 on 2023-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_info_drank'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='now_drink',
            field=models.FloatField(default=0),
        ),
    ]
