# Generated by Django 4.2.4 on 2023-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_now_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='now_drink',
            field=models.IntegerField(default=0),
        ),
    ]
